const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');
const fs = require('fs');
const path = require('path');

const db = {
  users: [
    {
      id: uuidv4(),
      username: 'admin',
      email: 'admin@dvfu-rectorat.ru',
      passwordHash: bcrypt.hashSync('admin123', 10),
      role: 'admin',
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      username: 'editor',
      email: 'editor@dvfu-rectorat.ru',
      passwordHash: bcrypt.hashSync('editor123', 10),
      role: 'editor',
      createdAt: new Date().toISOString(),
    },
  ],
  events: [
    {
      id: uuidv4(),
      type: 'event',
      title: 'XIV Форум ректоров «Роль университетов России и Китая в обеспечении технологического лидерства стран-партнеров»',
      date: '1 октября 2025',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Заседание',
      description: 'С 13 по 15 октября 2025 года в г. Хабаровске состоится XIV Форум ректоров вузов Дальнего Востока и Сибири России и Северо-восточных …',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'news',
      title: 'V Всероссийский межведомственный научно-практический антинаркотический форум «Актуальные вопросы аддиктологии»',
      date: '16 марта 2026',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Соглашение',
      description: '26 февраля в СПбГЭУ пройдет II Всероссийская научно-практическая конференция с международным участием «Цифровые технологии:',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'event',
      title: 'Ученые ДВФУ и СахГУ создали «идеальный» материал для сердца водородного двигателя',
      date: '19 марта 2026',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Конференция',
      description: 'Инновационный керамический материал, который может стать основой для создания более эффективных и долговечных элементов водородной энергетики',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'news',
      title: 'Открыт набор волонтеров на XI Восточный экономический форум ',
      date: '18 марта 2026',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Программа',
      description: 'Стартовал набор волонтеров для участия в подготовке и проведении Восточного экономического форума',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'event',
      title: 'Круглый стол по цифровизации образования',
      date: '25 октября 2024',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Круглый+стол',
      description: 'Проведен круглый стол с участием руководителей IT-подразделений вузов по вопросам внедрения цифровых технологий.',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'news',
      title: 'Результаты конкурса студенческих проектов',
      date: '20 октября 2024',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Конкурс',
      description: 'Подведены итоги ежегодного конкурса студенческих проектов. Победители получили гранты на реализацию своих инициатив.',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  pressReleases: [
    {
      id: uuidv4(),
      title: 'Итоги заседания Совета ректоров ДФО',
      date: '15.11.2024',
      content: 'Краткое описание пресс-релиза...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Новая программа развития образования',
      date: '10.11.2024',
      content: 'Краткое описание пресс-релиза...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Подписание соглашения о сотрудничестве',
      date: '05.11.2024',
      content: 'Краткое описание пресс-релиза...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  announcements: [
    {
      id: uuidv4(),
      title: 'Предстоящее заседание Совета ректоров',
      date: '25.11.2024',
      content: 'Информация о предстоящем мероприятии...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Международная конференция',
      date: '01.12.2024',
      content: 'Анонс международной конференции...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  photos: [
    {
      id: uuidv4(),
      title: 'Заседание Совета ректоров',
      date: '15.11.2024',
      image: 'https://via.placeholder.com/400x300/1e4976/FFFFFF?text=Фото+1',
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Подписание соглашения',
      date: '10.11.2024',
      image: 'https://via.placeholder.com/400x300/1e4976/FFFFFF?text=Фото+2',
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Конференция по образованию',
      date: '05.11.2024',
      image: 'https://via.placeholder.com/400x300/1e4976/FFFFFF?text=Фото+3',
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Круглый стол',
      date: '01.11.2024',
      image: 'https://via.placeholder.com/400x300/1e4976/FFFFFF?text=Фото+4',
      published: true,
      createdAt: new Date().toISOString(),
    },
  ],
  videos: [
    {
      id: uuidv4(),
      title: 'Репортаж с заседания Совета',
      date: '15.11.2024',
      thumbnail: 'https://via.placeholder.com/400x250/1e4976/FFFFFF?text=Видео+1',
      videoUrl: '',
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Интервью с председателем',
      date: '10.11.2024',
      thumbnail: 'https://via.placeholder.com/400x250/1e4976/FFFFFF?text=Видео+2',
      videoUrl: '',
      published: true,
      createdAt: new Date().toISOString(),
    },
  ],
  documents: [
    {
      id: uuidv4(),
      category: 'История',
      title: 'История создания Совета ректоров вузов ДФО',
      file: 'history.pdf',
      date: '2020',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'История',
      title: 'Основные этапы развития',
      file: 'stages.pdf',
      date: '2021',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'Учредительные документы',
      title: 'Положение о Совете ректоров вузов ДФО',
      file: 'regulation.pdf',
      date: '2024',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'Учредительные документы',
      title: 'Устав Совета ректоров вузов ДФО',
      file: 'charter.pdf',
      date: '2024',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};

fs.writeFileSync(
  path.join(__dirname, 'db.json'),
  JSON.stringify(db, null, 2),
  'utf-8'
);

console.log('База данных создана успешно!');
console.log('Пользователи:');
console.log('  admin / admin123 (администратор)');
console.log('  editor / editor123 (редактор)');
